version: '3.8'

services:

 wannabe-back:
    image: wannabe-back
    restart: always
    ports:
      - 8081:8081
    container_name: wannabe-back
    environment:
      # Important for clients to register with eureka
      - server.port=8081
      - spring.profiles.active=dev
    networks:
      - timomctimo

networks:
  timomctimo:
    external : true